### ISSUE TITLE
Make it easier to use this app for simple reproductions of bugs

### ISSUE THREAD

**Issue by janpio** [apache/cordova-app-hello-world#31]
When a user has a bug with some plugin, we often ask them to create a new project using `cordova create` (which will use this template by default). Currently it is not very easy to adapt the layout and content to for example add a few buttons or output of some values because of the design. Also it is not super easy to add JS code in the correct place of the setup.

**Comment by janpio** [comment]
https://github.com/apache/cordova-app-hello-world/pull/9 actually simplifies the `index.js` a lot (but is unfortunately conflicted - but could sure be used as a base).

**Comment by jcesarmobile** [comment]
The js was simplified in a different PR, I think this can be closed
