### ISSUE TITLE
Simplify the generated Cordova project

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-app-hello-world#53]
# Feature Request

## What

- [x] generated JavaScript should be functional, see the following for an example: <https://github.com/brodybits/cordova-dialogs-bootstrap-starter-app/blob/master/www/app.js>
- [x] I think we should check that both `plugins` and `platforms` are in `.gitignore`
- [x] ensure there is no `.npmignore`
- [x] I think generated project should have a limited number of artifacts, for example: `config.xml`, `package.json`, `.gitignore`, `README.md`, and `www` directory limited to `index.html` & `index.js` or `app.js` (see <https://github.com/brodybits/cordova-dialogs-bootstrap-starter-app> for an example)

## Motivation Behind Feature

I have seen too many app developers write convoluted JavaScript starting with the object in the generated `app.js` file. In contrast, recent versions of React / React Native seem to generate more functional JavaScript, IIRC.

I think that in general, the main Cordova JavaScript function should do something like `document.addEventListener('deviceready', appMainStartupFunction)` wherever approapriate. Clean and simple.

## Feature Description

See [What](#what)

## Alternatives or Workarounds

- Document the cleaner, more functional approach somewhere

**Comment by raphinesse** [comment]
IMHO we have all the boxes ticked except for the last one. Would #9 match the criteria for the first item?

**Comment by brodybits** [comment]
I think so.

**Comment by jcesarmobile** [comment]
Closing since al checkboxes are checked
