### ISSUE TITLE
wanting to add some tweaks in UI with animation with appreciable hover effect and many more...

### ISSUE THREAD

**Issue by Ashish9836** [apache/cordova-app-hello-world#69]
after seeing your project Cordova- app-hello-world , i will be  pleased to add some tweaks in this project 
so i will try to add amazing and efficient things to enhnace the user experience of this project.

**Comment by Rohan749** [comment]
I have experience in the animation field, hover effects, and transition effects, and would love to work on this issue.

**Comment by jcesarmobile** [comment]
The app is very simple and we want to keep it that way since this is just the starting point.
Also hover doesn’t work on mobile.
