### ISSUE TITLE
Add Github actions example

### ISSUE THREAD

**Issue by bcopy** [apache/cordova-app-hello-world#71]
# Feature Request

## Motivation Behind Feature
It would be nice to have a working example of how to produce application distribution packages via Github Actions.
For instance using this existing action (for APK) : https://github.com/oxr463/setup-cordova

## Feature Description

Please add an example Github action workflow to assemble the Cordova application and release it as a Github download.
This is helpful to automate the assembly and distribution of one's application.

## Alternatives or Workarounds

Currently, users have to build their application locally, then upload it to Github or an application store of their choice.

**Comment by breautek** [comment]
My initial thoughts on this, Cordova already provides documentation on how to build release builds of your apps in each of the platforms. Providing documentation on how to integrate those into a particular CI environment, and maintaining it for accuracy as time goes on seems out of scope for Apache to me. I think guides like this is better in user/community land.

Most CI environments simply runs command line scripts anyway. So the process would be learning for your CI of choice of how to supply secret files, such as the android key store for signing apks / bundles, or apple id credentials for obtaining the signing certificates and uploading, and then running the particular set of commands to generate the workspace and build.

**Comment by jcesarmobile** [comment]
I agree, this is out of the scope
